spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 123456
    platform: mysql
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
##      javax:
##        persistence:
##          schema-generation:
##            create-source: metadata
##            scripts:
##              action: create
##              create-target: guru_database_create.sql